---
- name: Install Clickhouse
  hosts: clickhouse
  vars_files:
    - /root/08-ansible-03-yandex/playbook/group_vars/clickhouse/vars.yml
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/{{ item }}"
        dest: "/tmp/{{ item }}"
        mode: '0644'
      loop: "{{ clickhouse_packages }}"

    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - "/tmp/clickhouse-client-{{ clickhouse_version }}.noarch.rpm"
          - "/tmp/clickhouse-server-{{ clickhouse_version }}.noarch.rpm"
          - "/tmp/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
      notify: Start clickhouse service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install and Configure Vector
  hosts: vector
  vars_files:
    - /root/08-ansible-03-yandex/playbook/group_vars/vector/vars.yml
  tasks:
    - name: Download Vector RPM
      ansible.builtin.get_url:
        url: "{{ vector_rpm_url }}"
        dest: "/tmp/vector-{{ vector_version }}-1.x86_64.rpm"
        mode: '0644'

    - name: Install Vector RPM
      become: true
      ansible.builtin.yum:
        name: "/tmp/vector-{{ vector_version }}-1.x86_64.rpm"
        state: present

    - name: Deploy Vector Configuration
      become: true
      ansible.builtin.template:
        src: "{{ vector_config_template }}"
        dest: "{{ vector_config_destination }}"
        mode: '0644'

- name: Install and Configure LightHouse
  hosts: lighthouse
  vars:
    web_root: "/var/www/html" # Корневой каталог для файлов веб-сайта
  tasks:
    - name: Ensure git is installed
      become: true
      ansible.builtin.package:
        name: git
        state: present

    - name: Clone LightHouse repository
      become: true
      ansible.builtin.git:
        repo: "https://github.com/VKCOM/lighthouse.git"
        dest: "{{ web_root }}/lighthouse"
        version: master
        clone: true
        update: true

    - name: Enable EPEL repository
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Install Nginx
      become: true
      ansible.builtin.package:
        name: nginx
        state: present
    - name: Deploy Nginx Configuration
      become: true
      ansible.builtin.template:
        src: templates/web_server_config.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: '0644'
      notify: Restart Nginx

    - name: Start Nginx Service
      become: true
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
  handlers:
    - name: Restart Nginx
      become: true
      ansible.builtin.systemd:
        name: nginx
        state: restarted
